sonar.projectKey=webapp
sonar.projectName=WebApp

sonar.sources=application/frontend,application/backend

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/src/App.jsx,**/src/api.js

sonar.sourceEncoding=UTF-8