version: "3.9"

services:
  frontend:
    image: deekshithc1/frontend:${BUILD_NUMBER}
    build:
      context: ../application/frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:7000
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app_network

  backend:
    image: deekshithc1/backend:${BUILD_NUMBER}
    build:
      context: ../application/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "7000:7000"
    restart: unless-stopped
    environment:
      PORT: 7000
      NODE_ENV: development
      MONGO_URI: mongodb+srv://devuser:1234@cluster0.udec97z.mongodb.net/?appName=Cluster0
    networks:
      - app_network

networks:
  app_network:
    driver: bridge