pipeline {

    agent any

    environment {
        FRONTEND_IMAGE = "deekshithc1/frontend"
        BACKEND_IMAGE  = "deekshithc1/backend"
        NAMESPACE      = "webapp"
    }

    stages {

        stage("Checkout Source") {
            steps {
                checkout scm
            }
        }


        stage("Secret Detection - Gitleaks") {
            steps {
                sh '''
                    pwd
                    ls -la
                    bash scripts/git-leaks.sh
                '''
            }
        }


        stage("SonarQube Analysis") {
            steps {
                script {

                    def scannerHome = tool "SonarScanner"

                    withSonarQubeEnv("SonarQube") {

                        sh """
                            ${scannerHome}/bin/sonar-scanner
                        """
                    }
                }
            }
        }


        stage("SonarQube Quality Gate") {
            steps {

                timeout(time: 3, unit: 'MINUTES') {

                    waitForQualityGate abortPipeline: true
                }
            }
        }


        stage("Build Docker Images") {
            steps {

                sh '''
                    bash scripts/docker-build.sh
                '''
            }
        }


        stage("Trivy Image Scan") {
            steps {

                sh '''
                    bash scripts/trivy-scan.sh
                '''
            }
        }


        stage("DockerHub Login") {
            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {

                    sh '''
                        bash scripts/docker-login.sh
                    '''
                }
            }
        }


        stage("Push Docker Images") {
            steps {

                sh '''
                    bash scripts/docker-push.sh
                '''
            }
        }


        stage("Deploy to Kubernetes") {

            steps {

                withKubeConfig(credentialsId: 'my-kubeconfig') {

                    withCredentials([
                        usernamePassword(
                            credentialsId: 'mongodb-creds',
                            usernameVariable: 'MONGO_USER',
                            passwordVariable: 'MONGO_PASSWORD'
                        )
                    ]) {

                        sh '''
                            export MONGO_URI="mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@cluster0.udec97z.mongodb.net/?appName=Cluster0"

                            bash scripts/k8s-deploy.sh
                        '''
                    }
                }
            }
        }
    }


    post {


        success {

            echo """
=======================================
Pipeline Completed Successfully

Frontend Image : ${FRONTEND_IMAGE}:${BUILD_NUMBER}
Backend Image  : ${BACKEND_IMAGE}:${BUILD_NUMBER}

Application deployed successfully.
=======================================
"""


            emailext(
                subject: "SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
Hello Team,

The Jenkins pipeline has completed successfully.

Job Name      : ${env.JOB_NAME}
Build Number  : ${env.BUILD_NUMBER}
Build Status  : SUCCESS

Frontend Image:
${FRONTEND_IMAGE}:${BUILD_NUMBER}

Backend Image:
${BACKEND_IMAGE}:${BUILD_NUMBER}

Build URL:
${env.BUILD_URL}

Regards,
Jenkins CI/CD
""",
                to: "yourgmail@gmail.com"
            )
        }



        failure {

            echo """
=======================================
Pipeline Failed

Rolling back deployments...
=======================================
"""


            withKubeConfig(credentialsId: 'my-kubeconfig') {

                sh '''
                    if [ -f scripts/k8s-rollback.sh ]; then
                        bash scripts/k8s-rollback.sh
                    else
                        echo "Rollback script not found"
                    fi
                '''
            }


            emailext(
                subject: "FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
Hello Team,

The Jenkins pipeline has failed.

Job Name      : ${env.JOB_NAME}
Build Number  : ${env.BUILD_NUMBER}
Build Status  : FAILED

Rollback has been initiated.

Build URL:
${env.BUILD_URL}

Please check Jenkins logs.

Regards,
Jenkins CI/CD
""",
                to: "yourgmail@gmail.com"
            )
        }



        always {

            sh '''
                if [ -f scripts/cleanup.sh ]; then
                    bash scripts/cleanup.sh
                else
                    echo "Cleanup script not found"
                fi
            '''

            echo "Pipeline Finished"

            cleanWs()
        }
    }
}